services:
  backend:
    build: ./backend
    container_name: viaticos-backend
    restart: always
    ports:
      - "3026:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    networks:
      - viaticos-net

  frontend:
    build: ./frontend
    container_name: viaticos-frontend
    restart: always
    ports:
      - "3027:80"
    depends_on:
      - backend
    networks:
      - viaticos-net

networks:
  viaticos-net:
    driver: bridge
