-- Crear tabla para excepciones de firmas (firmas de área que se excluyen para un empleado específico)
CREATE TABLE IF NOT EXISTS public.excepciones_firmas_empleado
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_empleado integer NOT NULL,
    id_firma integer NOT NULL,
    fecha_exclusion timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT excepciones_firmas_empleado_pkey PRIMARY KEY (id),
    CONSTRAINT excepciones_firmas_empleado_id_empleado_fkey FOREIGN KEY (id_empleado)
        REFERENCES public.empleados (id_empleado) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT excepciones_firmas_empleado_id_firma_fkey FOREIGN KEY (id_firma)
        REFERENCES public.firmas (id_firma) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.excepciones_firmas_empleado OWNER to postgres;

COMMENT ON COLUMN public.excepciones_firmas_empleado.id IS 'ID único';
COMMENT ON COLUMN public.excepciones_firmas_empleado.id_empleado IS 'Empleado para el cual se excluye la firma';
COMMENT ON COLUMN public.excepciones_firmas_empleado.id_firma IS 'Firma de área excluida';
