const pool = require('../config/database');

async function insertPuestos() {
    const puestos = [
        'SECRETARIO DE ESTADO O EQUIVALENTE', 'DIRECTOR GENERAL', 'SECRETARIO DEL EJECUTIVO',
        'SUBSECRETARIO DE ESTADO O EQUIVALENTE', 'SECRETARIO EJECUTIVO', 'COORDINADOR (A) GENERAL DE RECURSOS HUMANOS',
        'COORDINADOR Ó EQUIVALENTE', 'DIRECTOR ACADEMIA DE POLICÍA', 'DIRECTOR', 'JEFE DE UNIDAD',
        'CONTRALOR INTERNO', 'SECRETARIO TÉCNICO COORDINADOR TÉCNICO', 'ASESOR A', 'SECRETARIO PARTICULAR',
        'ASESOR B', 'COORDINADOR', 'COORDINADOR JURÍDICO', 'COORDINADOR SOCIAL',
        'REPRESENTANTE OPERATIVO PARA LA OBRA PÚBLICA', 'RESPONSABLE ANTE EL COMITÉ DE ADQUISICIONES',
        'CONSEJERO', 'ASISTENTE DE INGENIERÍA AERONÁUTICA', 'SUPERVISOR DE HELICÓPTEROS',
        'TÉCNICO MECÁNICO DE ALA FIJA', 'TÉCNICO MECÁNICO DE ALA ROTATIVA', 'SUPERVISOR DE MANTENIMIENTO DE AERONAVES',
        'TÉCNICO DE ACABADOS DE AERONAVES', 'TÉCNICO EN AVIONIC\'S', 'ASESOR C', 'OFICIAL DEL REGISTRO CIVIL DEL ESTADO',
        'SUBDIRECTOR DE LA ACADEMIA DE POLICÍA', 'DELEGADO ADMINISTRATIVO', 'DELEGADO DE TRÁNSITO',
        'RESPONSABLE DE RECAUDACIÓN LOCAL', 'SUBDIRECTOR', 'JEFE DE DEPARTAMENTO', 'COORDINADOR OPERATIVO',
        'DELEGADO', 'PRESIDENTE DE LA JUNTA LOCAL DE CONCILIACIÓN', 'COMANDANTE OPERATIVO',
        'DELEGADO DE INGRESOS', 'CURADOR GENERAL', 'JEFE DE ÁREA DE CONTRALORIA', 'JEFE DE DEPARTAMENTO DE CONTRALORIA',
        'DELEGADO DE HACIENDA', 'COPILOTO', 'CURADOR DE ZOOLÓGICO', 'PILOTO A', 'PILOTO B', 'PILOTO C',
        'ANÁLISIS TÉCNICO ESPECIALIZADO', 'SUBDIRECTOR ADMINISTRATIVO', 'JEFE DE OFICINA', 'JEFE DE ÁREA',
        'AGENTE DEL MINISTERIO PÚBLICO', 'JEFE TÉCNICO PEDAGÓGICO', 'DIRECTOR MÚSICO', 'SUPERVISOR DE OBRA',
        'AUDITOR A', 'ANALISTA TÉCNICO EN CONTABILIDAD', 'AUDITOR B', 'SUPERVISOR DE EDUCACIÓN',
        'SUPERVISOR DE PRODUCCIÓN', 'SUBCOMANDANTE DE REGIÓN', 'JEFE DE OPERACIÓN', 'ASISTENTE DE ÁREA',
        'JEFE DE SECCIÓN', 'JEFE ADMINISTRATIVO', 'SUBDELEGADO ADMINISTRATIVO', 'AGENTE DEL MINISTERIO PÚBLICO AUXILIAR',
        'SUPERVISOR DE AUDITOR', 'ANALISTA TÉCNICO B', 'ANALISTA TÉCNICO C', 'JEFE DE CUADRILLA', 'SUPERVISOR',
        'JEFE DE OPERACIONES', 'SEGUNDO OFICIAL Y/O POLICIA PRIMERO', 'COORDINADOR DE GRUPO', 'JEFE DE GRUPO',
        'ALCALDE', 'MÚSICO GENERAL', 'NOTIFICADOR Y EJECUTOR', 'TRADUCTOR DE LENGUAS', 'ACTUARIO NOTIFICADOR',
        'PROMOTOR', 'TOPÓGRAFO', 'PROMOTOR DEPORTIVO', 'PERITO A', 'TRABAJADORA SOCIAL', 'CAPTURISTA',
        'LOCUTOR', 'AGENTE DE INFORMACIÓN BILINGÜE', 'ANALISTA PROGRAMADOR', 'REPORTERO', 'CORRESPONSAL',
        'PSICÓLOGO', 'PERITO B', 'MECÁNICO DE AERONAVE', 'INSTRUCTOR', 'ANALISTA DE SISTEMAS',
        'INSTRUCTOR DE TALLER DE EDUCACIÓN ESPECIAL', 'INSTRUCTOR DE EDUCACIÓN ESPECIAL', 'INVESTIGADOR',
        'COORDINADOR ADMINISTRATIVO (DELEGACIÓN)', 'OFICIAL SECRETARIO DEL MINISTERIO PÚBLICO', 'PROFESIONISTA A',
        'PROFESIONISTA B', 'ANALISTA TÉCNICO A', 'PROFESIONISTA C', 'OPERADOR', 'MECÁNICO', 'ANALISTA DE OPERACIÓN',
        'TÉCNICO MEDIO A', 'ANALISTA DE MAQUINARIA PESADA', 'CAMARÓGRAFO', 'TÉCNICO EN ELECTRÓNICA', 'PROYECTISTA',
        'DIBUJANTE', 'MECÁNICO ESPECIALIZADO', 'TÉCNICO MEDIO B', 'OPERADOR DE TRAILER', 'TÉCNICO MEDIO C',
        'TÉCNICO ESPECIALIZADO', 'TÉCNICO DE TRANSMISIÓN', 'REPRESENTANTE', 'INSPECTOR', 'JEFE DE FISCAL',
        'AGENTE FISCAL', 'AUXILIAR ADMINISTRATIVO', 'ADMINISTRADOR DOCUMENTAL', 'AUXILIAR ADMINISTRATIVO DE SUPERVISOR',
        'PREFECTO', 'AUXILIAR DE SUPERVISOR DE TELESECUNDARIA', 'AGENTE DE INFORMACIÓN', 'SECRETARIA EJECUTIVA DE APOYO',
        'AUXILIAR ADMINISTRATIVO DE TELESECUNDARIA', 'RECEPCIONISTA', 'RESPONSABLE DE SECCIÓN', 'RESPONSABLE DE MESA',
        'GESTOR ADMINISTRATIVO', 'SECRETARIA EJECUTIVA DE MANDO MEDIO', 'CAJERA', 'AUXILIAR CONTABLE',
        'EVALUADOR CONTABLE', 'SECRETARIA EJECUTIVA DE MANDO SUPERIOR', 'VIGILANTE', 'VIGILANTE DE ZOOLOGÍA Y BOTÁNICA',
        'ELECTRICISTA', 'CARPINTERO', 'SOLDADOR', 'CADENERO', 'AUXILIAR DE LABORATORIO', 'ARTESANO',
        'ENCARGADO DE TALLER', 'HERRERO', 'AYUDANTE', 'MENSAJERO', 'INSTITUTRIZ', 'JARDINERO ESPECIALIZADO',
        'CHOFER DE APOYO', 'MANTENEDOR DE ANIMALES', 'CHOFER DE MANDO MEDIO', 'CHOFER DE MANDO SUPERIOR'
    ];

    try {
        await pool.query('BEGIN');
        await pool.query('TRUNCATE TABLE puestos RESTART IDENTITY CASCADE');

        for (const nombre of puestos) {
            await pool.query('INSERT INTO puestos (nombre_puesto) VALUES ($1)', [nombre]);
        }

        await pool.query('COMMIT');
        console.log(`✅ Se insertaron ${puestos.length} puestos exitosamente.`);

        const res = await pool.query('SELECT COUNT(*) FROM puestos');
        console.log(`Conteo final en DB: ${res.rows[0].count}`);

    } catch (err) {
        await pool.query('ROLLBACK');
        console.error('❌ Error insertando puestos:', err.message);
    } finally {
        await pool.end();
    }
}

insertPuestos();
