const pool = require('../config/database');

async function reconstructVehiculos() {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        console.log('1. Eliminando tablas antiguas (CASCADE)...');
        // Eliminar con CASCADE para limpiar llaves foráneas que apunten a estas
        await client.query('DROP TABLE IF EXISTS public.vehiculos CASCADE');
        await client.query('DROP TABLE IF EXISTS public.marcas_de_vehiculos CASCADE');
        await client.query('DROP TABLE IF EXISTS public.tipos_de_vehiculos CASCADE');
        await client.query('DROP TABLE IF EXISTS public.clases_de_vehiculos CASCADE');
        await client.query('DROP TABLE IF EXISTS public.estatus_de_vehiculos CASCADE');
        await client.query('DROP TABLE IF EXISTS public.usos_de_vehiculos CASCADE'); // Nombre viejo
        await client.query('DROP TABLE IF EXISTS public.usos_del_vehiculo CASCADE'); // Nombre nuevo por si acaso

        console.log('2. Creando nuevas tablas...');

        // Tabla de usos de vehículos
        await client.query(`
            CREATE TABLE public.usos_del_vehiculo
            (
                id_uso_del_vehiculo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                uso_del_vehiculo text NOT NULL,
                esta_borrado boolean NOT NULL DEFAULT false,
                CONSTRAINT usos_del_vehiculo_pkey PRIMARY KEY (id_uso_del_vehiculo)
            );
        `);

        // Tabla de estatus de vehículos
        await client.query(`
            CREATE TABLE public.estatus_de_vehiculos
            (
                id_estatus_de_vehiculo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                estatus_de_vehiculo text NOT NULL,
                esta_borrado boolean NOT NULL DEFAULT false,
                CONSTRAINT estatus_de_vehiculos_pkey PRIMARY KEY (id_estatus_de_vehiculo)
            );
        `);

        // Tabla de clases de vehículos
        await client.query(`
            CREATE TABLE public.clases_de_vehiculos
            (
                id_clase_de_vehiculo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                clase_de_vehiculo text NOT NULL,
                esta_borrado boolean NOT NULL DEFAULT false,
                CONSTRAINT clases_de_vehiculos_pkey PRIMARY KEY (id_clase_de_vehiculo)
            );
        `);

        // Tabla de tipos de vehículos
        await client.query(`
            CREATE TABLE public.tipos_de_vehiculos
            (
                id_tipo_de_vehiculo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                tipo_de_vehiculo text NOT NULL,
                esta_borrado boolean NOT NULL DEFAULT false,
                CONSTRAINT tipos_de_vehiculos_pkey PRIMARY KEY (id_tipo_de_vehiculo)
            );
        `);

        // Tabla de marcas de vehículos
        await client.query(`
            CREATE TABLE public.marcas_de_vehiculos
            (
                id_marca_de_vehiculo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                marca_de_vehiculo text NOT NULL,
                esta_borrado boolean NOT NULL DEFAULT false,
                CONSTRAINT marcas_de_vehiculos_pkey PRIMARY KEY (id_marca_de_vehiculo)
            );
        `);

        // Tabla de vehículos (vinculada a empleados e id_uso_del_vehiculo)
        await client.query(`
            CREATE TABLE public.vehiculos
            (
                id_vehiculo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                id_estructura_administrativa integer NOT NULL,
                numero_economico text,
                id_marca_de_vehiculo integer NOT NULL,
                id_tipo_de_vehiculo integer NOT NULL,
                id_clase_de_vehiculo integer NOT NULL,
                modelo text,
                placas_anteriores text,
                placas_actuales text,
                numero_de_motor text,
                serie text,
                id_estatus_de_vehiculo integer NOT NULL,
                id_uso_del_vehiculo integer NOT NULL,
                id_empleado integer,
                esta_borrado boolean NOT NULL DEFAULT false,
                CONSTRAINT vehiculos_pkey PRIMARY KEY (id_vehiculo),
                CONSTRAINT fk_vehiculos_id_marca FOREIGN KEY (id_marca_de_vehiculo) REFERENCES public.marcas_de_vehiculos (id_marca_de_vehiculo),
                CONSTRAINT fk_vehiculos_id_tipo FOREIGN KEY (id_tipo_de_vehiculo) REFERENCES public.tipos_de_vehiculos (id_tipo_de_vehiculo),
                CONSTRAINT fk_vehiculos_id_clase FOREIGN KEY (id_clase_de_vehiculo) REFERENCES public.clases_de_vehiculos (id_clase_de_vehiculo),
                CONSTRAINT fk_vehiculos_id_estatus FOREIGN KEY (id_estatus_de_vehiculo) REFERENCES public.estatus_de_vehiculos (id_estatus_de_vehiculo),
                CONSTRAINT fk_vehiculos_id_uso FOREIGN KEY (id_uso_del_vehiculo) REFERENCES public.usos_del_vehiculo (id_uso_del_vehiculo),
                CONSTRAINT fk_vehiculos_id_empleado FOREIGN KEY (id_empleado) REFERENCES public.empleados (id_empleado)
            );
        `);

        console.log('3. Poblando catálogos...');

        await client.query("INSERT INTO public.usos_del_vehiculo (uso_del_vehiculo) VALUES ('OFICIAL'), ('COMO DATO')");
        await client.query("INSERT INTO public.estatus_de_vehiculos (estatus_de_vehiculo) VALUES ('BUENO'), ('REGULAR')");
        await client.query("INSERT INTO public.clases_de_vehiculos (clase_de_vehiculo) VALUES ('CAMIÓN'), ('MOTOCICLETA'), ('PICK UP'), ('PICK-UP'), ('REDILAS'), ('SEDAN'), ('SUV'), ('VAN')");

        const tipos = ['AVEO', 'CHARGER', 'CHASIS CABINA', 'CHASIS CABINA/REDILAS', 'CHEVY', 'COMPASS', 'COROLLA', 'CRV-EX', 'DOBLE CABINA', 'DOMINAR 400', 'F-150', 'FIGO IMPULSE', 'FRONTIER', 'FRONTIER SE', 'FZ-S FI 2.0', 'GIANT MOTORS SEI', 'GOL', 'GRAND CHEROKEE', 'HIACE CONMUTER', 'HIGHLANDER', 'JETTA', 'JETTA COMFORLINE', 'JETTA GLI', 'JETTA SPORTLINE', 'L200', 'L200 DIESEL', 'LOGAN', 'MALIBÚ', 'PASSAT', 'PASSAT BLINDADO', 'PICK-UP', 'POLO', 'RAM 1500', 'REDILAS', 'S10 MAX', 'SENTRA', 'SEQUOIA PLATINUM', 'SUBURBAN', 'SUBURBAN HIGH COUNTRY', 'SUBURBAN RST', 'SUPER DUTY F-350', 'SUPER DUTY F-450 XL', 'TAHOE 4X2', 'TIIDA', 'TORNADO', 'TOWN & COUNTRY', 'URVAN', 'VENTO', 'VIRTUS', 'X-TRAIL SENSE', 'YARIS'];
        for (let t of tipos) await client.query("INSERT INTO public.tipos_de_vehiculos (tipo_de_vehiculo) VALUES ($1)", [t]);

        const marcas = ['BAJAJ', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FORD', 'FREIGHTLINER', 'HONDA', 'INTERNATIONAL', 'JAC', 'JEEP', 'MITSUBISHI', 'NISSAN', 'RENAULT', 'TOYOTA', 'VOLKSWAGEN', 'YAMAHA'];
        for (let m of marcas) await client.query("INSERT INTO public.marcas_de_vehiculos (marca_de_vehiculo) VALUES ($1)", [m]);

        console.log('4. Poblando vehículos...');
        const vehiculosData = [
            [1, '211110102023026', 14, 19, 8, '2023', null, 'DRU-557-H', '7GRN161431', 'JTFJM9CP1P6006166', 1, 1, 279],
            [1, '2111101020230160', 14, 19, 8, '2023', null, 'DRU-558-H', '7GRN169617', 'JTFJM9CP8P6007296', 1, 1, 279],
            [1, '20100050030', 12, 36, 6, '1999', null, 'DRU-560-H', 'GA16729479P', '3N1DB41S5XK053124', 2, 1, 205],
            [1, '21100050024', 12, 36, 6, '2002', null, 'DRU-571-H', 'QG18568216R', '3N1CB51S32K220588', 2, 1, 205],
            [1, '25200050047', 5, 42, 1, '2003', null, 'CW-7645-J', 'NO ESPECIFICA', '3FDXF46S73MB10523', 2, 1, 205],
            [1, '20100050067', 7, 8, 8, '2005', null, 'DRU-563-H', 'K24A14902674', 'JHLRD78715C601514', 2, 1, 205],
            [1, '20100080001', 2, 28, 6, '2008', null, 'DRU-568-H', '8F156028', '1G1ZH57788F156028', 2, 1, 205],
            [1, '20100090008', 15, 29, 6, '2009', null, 'DRU-575-H', 'CCT092889', 'WVWHL73C09E564160', 2, 1, 205],
            [1, '20100100013', 2, 5, 6, '2010', null, 'DRU-562-H', 'AS141773', '3G1SF21XXAS141773', 2, 1, 205],
            [1, '20100100021', 2, 38, 8, '2010', null, 'DRU-564-H', 'AR278267', '1GNUCJE08AR278267', 2, 1, 205],
            [1, '20100100016', 2, 38, 8, '2010', null, 'DRU-566-H', 'AR2771939', '1GNUCJE05AR277139', 2, 1, 205],
            [1, '20100100026', 2, 28, 6, '2010', null, '337-XHB', 'AF200850', '1G1ZE5E70AF200850', 2, 1, 205],
            [1, '23300150001', 11, 26, 4, '2010', null, 'CX-6656-G', 'UCBT9593', 'MMBNG45K7ADZ00594', 2, 1, 205],
            [1, '23300150002', 11, 26, 4, '2010', null, 'CX-6657-G', 'UCBR9159', 'MMBNG45K5ADZ00173', 2, 1, 205],
            [1, '20100100019', 2, 43, 8, '2010', null, 'DRU-572-H', 'AR269185', '1GNUCAE05AR269185', 2, 1, 205],
            [1, '20100100020', 3, 46, 8, '2010', null, '430-XEZ', 'HECHO EN U.S.A.', '2A4RR6DX3AR352174', 2, 1, 205],
            [1, '20100100028', 4, 2, 6, '2010', null, '697-XHW', 'HECHO EN U.S.A', '2B3CA3CV9AH281717', 2, 1, 205],
            [1, '20100100001', 7, 8, 8, '2010', null, 'DRU-561-H', 'K24Z61510237', '3CZRE3850AG003966', 2, 1, 205],
            [1, '23003110003', 6, 3, 1, '2010', null, null, 'NO ESPECIFICA', '3ALACYCSXADAR0541', 2, 1, null],
            [1, '20100100027', 4, 2, 6, '2010', null, 'DRU-583-H', 'HECHO EN USA', '2B3CA3CV5AH281715', 2, 1, 205],
            [1, '20100100029', 4, 2, 6, '2010', null, 'DRU-581-H', 'HECHO EN USA', '2B3CA3CV2AH281719', 2, 1, 205],
            [1, '23003110001', 5, 41, 1, '2011', null, null, 'NO ESPECIFICA', '1FDGF4GY7BEB28916', 2, 1, null],
            [1, '23300110003', 2, 1, 6, '2011', null, 'DRU-582-H', 'HECHO EN MÉXICO', '3G1TA5AF5BL119011', 2, 1, 205],
            [1, '´211110102021099', 12, 4, 5, '2022', null, 'CX-6658-G', 'QR25436236H', '3N6AD35A0NK813377', 1, 1, 205],
            [1, '211110102023022', 2, 35, 4, '2023', null, 'CX-6659-G', 'HECHO EN CHINA', 'LSFAM3AB6PA060243', 1, 1, 205],
            [1, '20100100004', 15, 21, 6, '2010', null, 'DRU-574-H', 'CBP162319', '3VWRV09M1AM037441', 2, 1, 188],
            [1, '21000140001', 2, 38, 8, '2015', null, 'DPM-678-H', 'HECHO EN USA', '1GNSC8KC6FR196723', 2, 1, 177],
            [1, '´2111101020220162', 13, 27, 6, '2023', null, 'DNF-994-H', 'Q162885', '9FB4SR0E2PM399835', 1, 1, 254],
            [1, '20100050020', 2, 31, 4, '1998', null, 'CX-6661-G', 'IMPORTADO', '1GCEC2479WZ127348', 2, 1, 38],
            [1, '23300150003', 11, 26, 4, '2010', null, 'CX-4671-G', 'UCBU8883', 'MMBNG45K6ADZ01736', 2, 1, 38],
            [1, '20100100022', 2, 38, 8, '2010', null, 'DRU-565-H', 'AR287163', '1GNUCJE08AR287163', 2, 1, 38],
            [1, '20100100024', 8, 34, 1, '2011', null, 'CX-4670-G', '466HM2N8005006', '3HAMMAAR6BL344930', 2, 1, 38],
            [1, '20100100025', 8, 34, 1, '2011', null, 'CX-4668-G', '466HM2N8004998', '3HAMMAAR6BL344927', 2, 1, 38],
            [1, '20100200001', 11, 25, 4, '2021', null, 'CW-7644-J', 'UAJ0554', 'MMBML45G3MH007743', 1, 1, 38],
            [1, '21111010202305', 2, 35, 4, '2023', null, 'CX-4669-G', 'HECHO EN CHINA', 'LSFAM3AB4PA061360', 1, 1, 149],
            [1, '20100200003', 1, 10, 2, '2021', null, '40HCX6', 'JFYCLD51598', 'MD2A67MYXMCD00142', 1, 1, 40],
            [1, '´21111012021071', 15, 48, 6, '2021', null, 'DPM-679-H', 'CLS825180', 'MEX5B2608MT141817', 1, 1, 40],
            [1, '211110102022095', 1, 10, 2, '2022', null, '39HCX6', 'JFXCNM12570', 'MD2A67MX9NCM88819', 1, 1, 40],
            [1, '´2111101020220160', 16, 15, 2, '2022', null, '12HEG8', 'G3M6E0032686', 'ME1RG2682N3016817', 1, 1, 40],
            [1, '2111101020230159', 10, 18, 7, '2023', null, 'DPM-677-H', 'HECHO EN USA', '1C4RJGBGXPC623304', 1, 1, 40],
            [1, '201000080003', 14, 20, 8, '2008', null, 'DPM-676-H', '2GRA240493', 'JTEDS41A282008378', 2, 1, 20],
            [1, '20100100017', 2, 43, 8, '2010', null, 'DRU-567-H', 'AR245544', '1GNUCBE00AR245544', 2, 1, 20],
            [296, '22300120070', 12, 44, 6, '2012', null, 'DRU-585-H', 'MR18845553H', '3N1BC1AS7CK232472', 2, 2, 205],
            [296, '22300120052', 15, 17, 6, '2012', null, 'DRU-580-H', 'CFZ109690', '9BWDB05U3CT147428', 2, 2, 195],
            [296, '22300120067', 12, 44, 6, '2012', null, 'DRU-578-H', 'MR18845483H', '3N1BC1AS3CK232436', 2, 2, 272],
            [296, '22300120043', 15, 21, 6, '2012', null, 'DRU-584-H', 'CBP199151', '3VWBV49M1CM041789', 2, 2, 279],
            [707, '863', 15, 49, 6, '2020', null, 'DNH-624-H', 'CWS535459', '9BWDL5BZ9LP127672', 1, 2, 168],
            [296, '2111123020240278', 15, 24, 6, '2024', null, 'DPM-675-H', 'DSJ096884', '3VWRP6BU9RM023340', 1, 2, 166],
            [296, '22300120075', 12, 44, 6, '2012', null, 'DNH-673-H', 'MR18847827H', '3N1BC1ASXCK234393', 2, 2, 40],
            [296, '2111123020210264', 12, 50, 7, '2017', null, 'CS-488A-3', 'QR25873740L', 'JN8BT27T8HW042585', 1, 2, 40],
            [296, '22300170006', 4, 33, 3, '2018', null, 'CX-5855-G', 'MÉXICO', '3C6SRADGXJG123966', 1, 2, 40],
            [296, '2111123020210357', 15, 22, 6, '2019', null, 'DRD-824-H', 'CZD699513', '3VWWP6BU5KM099436', 1, 2, 40],
            [296, '´211112302021046', 14, 37, 8, '2021', null, 'DPM-674-H', '3UR6674997', '5TDYY5G13MS075740', 1, 2, 40],
            [296, '´211112302021047', 14, 37, 8, '2021', null, 'DPM-681-H', '3UR6675000', '5TDYY5G15MS075738', 1, 2, 40],
            [296, '´223002021030', 2, 39, 8, '2021', null, 'DPM-680-H', 'NO ESPECIFICA', '1GNSK9KL9MR187410', 1, 2, 40],
            [296, '´223002021029', 15, 23, 6, '2021', null, 'DPM-673-H', 'CXD062693', '3VW4E6BU4MM030379', 1, 2, 40],
            [296, '2111123020240279', 10, 18, 7, '2024', null, 'DPM-672-H', 'HECHO EN USA', '1C4RJGBG4RC684781', 1, 2, 40],
            [296, '2111123020240280', 10, 18, 7, '2024', null, 'DPM-671-H', 'HECHO EN USA', '1C4RJGBG2RC684780', 1, 2, 40],
            [296, '22300120055', 15, 17, 6, '2012', null, 'DLH-812-K', 'CFZ883491', '9BWDB05U0CT147581', 2, 2, 38],
            [296, '22300170022', 2, 1, 6, '2018', null, 'DNF-992-H', 'HECHO EN MÉXICO', '3G1TA5CFXJL186649', 1, 2, 38],
            [296, '22300200018', 12, 47, 8, '2020', null, 'DNF-991-H', 'QR25768409Q', 'JN1BE6DS9L9039682', 1, 2, 38],
            [296, '22300200019', 12, 47, 8, '2020', null, 'DNF-993-H', 'QR25760914Q', 'JN1BE6DS1L9038381', 1, 2, 38],
            [707, '720', 14, 7, 6, '2016', null, 'DNH-436-H', '2ZRL920921', '5YFBURHE1GP419105', 2, 2, 260],
            [707, '636', 15, 30, 6, '2015', null, 'DNH-435-H', 'CDV021486', '1VWCM7A33FC015471', 2, 2, 6],
            [419, null, 10, 6, 7, '2025', null, 'DPL-725-K', 'HECHO EN BRASIL', '988675423SKV60230', 1, 2, 6],
            [816, '25300170002', 2, 45, 4, '2006', null, 'CZ-9707-H', '6C139976', '93CXM80256C139976', 2, 2, 177],
            [707, '637', 15, 30, 6, '2015', null, 'DNH-605-H', 'CDV021903', '1VWCM7A34FC025085', 2, 2, 177],
            [707, '955', 5, 12, 6, '2021', null, 'DNH-576-H', 'NO APLICA', 'MAJFP1M16MA210039', 1, 2, 177],
            [419, null, 2, 40, 8, '2025', null, 'DPL-734-K', 'HECHO EN ESTADOS UNIDOS', '1GNS69RD9SRJ95643', 1, 2, 177],
            [419, null, 15, 21, 6, '2026', null, 'DPL-731-K', 'DSJ211831', '3VWEP6BU1TM017652', 1, 2, 177],
            [419, null, 15, 21, 6, '2026', null, 'DPL-733-K', 'DSJ212550', '3VWEP6BU2TM017871', 1, 2, 177],
            [69, '211111102021092', 15, 32, 6, '2021', null, 'DSM-855-H', 'CLS839807', 'MEX6B2607MT157530', 1, 2, 20],
            [69, '211111102023060', 14, 51, 6, '2023', null, 'DRS-760-H', '2NR5618275', 'MR2BF8C35P0003958', 1, 2, 20],
            [134, '21300050096', 2, 3, 5, '2003', null, 'CX-4672-G', '3M111809', '3GBJC34R63M111809', 2, 2, 38],
            [625, null, 12, 9, 4, '2005', null, 'CX-6369-G', 'KA24253067A', '3N6DD13S95K015957', 2, 2, 38],
            [25, '21000070006', 5, 11, 4, '2007', null, 'DB-4712-G', 'NO APLICA', '3FTGF17267MA27821', 2, 2, 38],
            [259, '22100070025', 5, 3, 5, '2008', null, 'CX-4667-G', 'NO APLICA', '3FEKF36L08MA04883', 2, 2, 38],
            [707, null, 12, 13, 4, '2016', null, 'DNF-612-H', 'NO APLICA', '3N6AD33A2GK880553', 2, 2, 38],
            [1065, '2112079020230130', 9, 16, 7, '2022', null, 'DRS-759-H', 'M3364716', 'LJ12EKS2XN4709731', 1, 2, 38],
            [419, null, 12, 14, 4, '2025', null, 'CZ-7382-J', 'QR25651771H', '3N6AD33A3SK847439', 1, 2, 38],
            [419, null, 12, 14, 4, '2025', null, 'CZ-7383-J', 'QR25650657H', '3N6AD33A3SK847542', 1, 2, 38] // Corregido typo en serie final
        ];

        const insertQuery = `
            INSERT INTO vehiculos (
                id_estructura_administrativa, numero_economico, id_marca_de_vehiculo, 
                id_tipo_de_vehiculo, id_clase_de_vehiculo, modelo, 
                placas_anteriores, placas_actuales, numero_de_motor, 
                serie, id_estatus_de_vehiculo, id_uso_del_vehiculo, id_empleado
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
        `;

        for (const v of vehiculosData) {
            await client.query(insertQuery, v);
        }

        await client.query('COMMIT');
        console.log('✅ Reconstrucción exitosa.');

    } catch (error) {
        await client.query('ROLLBACK');
        console.error('❌ Error en reconstrucción:', error);
    } finally {
        client.release();
        await pool.end();
    }
}

reconstructVehiculos();
