const pool = require('../config/database');

async function insertData() {
    const queries = [
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('2', '26', '20', '18', '1', '90', '1', '22', '1', '001', 'Brindar asesorías y apoyo técnico en políticas, programas y proyectos estratégicos que requieran de atención o seguimiento especializado.', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '20', '20', '2', 'false');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('3', '26', '21', '18', '1', '90', '1', '48', '1', '001', 'Coordinación de actividades para la realización de actos y eventos oficiales.', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '38', '38', '2', 'false');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('4', '26', '22', '18', '1', '90', '1', '48', '1', '001', 'Seguimiento a las peticiones de la ciudadanía y de organismos públicos y privados', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '279', '279', '2', 'false');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('12', '25', '22', '18', '1', '90', '1', '48', '1', '002', 'Seguimiento a las peticiones de la ciudadanía y de organismos públicos y privados.', '1', '1', '12', '2025-04-01 00:00:00-06', '2025-12-31 00:00:00-06', '1', '1', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('5', '26', '22', '18', '1', '20', '1', '118', '6', '001', 'Promover acciones que contribuyan a una igualdad entre hombres y mujeres en el organismo.', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '279', '279', '2', 'false');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('15', '25', '9', '18', '1', '20', '1', '118', '6', '001', 'Administración de recursos humanos, materiales y financieros.', '2', '1', '12', '2025-01-01 00:00:00-06', '2025-12-31 00:00:00-06', '279', '279', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('7', '25', '13', '18', '1', '90', '1', '22', '1', '001', 'Brindar apoyo técnico y asesoría.', '2', '1', '12', '2025-01-01 00:00:00-06', '2025-12-31 00:00:00-06', '20', '20', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('9', '25', '20', '18', '1', '90', '1', '22', '1', '001', 'Brindar asesorías y apoyo técnico en políticas, programas y proyectos estratégicos que requieran de atención o seguimiento especializado.', '1', '1', '12', '2025-04-01 00:00:00-06', '2025-12-31 00:00:00-06', '20', '20', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('11', '25', '22', '18', '1', '20', '1', '118', '6', '001', 'Promover acciones que contribuyan a una igualdad entre hombres y mujeres en el organismo.', '1', '1', '12', '2025-04-01 00:00:00-06', '2025-12-31 00:00:00-06', '279', '279', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('13', '25', '23', '18', '1', '90', '1', '45', '1', '001', 'Seguimiento de las acciones del Gobierno del Estado de Chiapas en la Ciudad de México.', '1', '1', '12', '2025-04-01 00:00:00-06', '2025-12-31 00:00:00-06', '324', '324', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('10', '25', '21', '18', '1', '90', '1', '48', '1', '001', 'Coordinación de actividades para la realización de actos y eventos oficiales.', '1', '1', '12', '2025-04-01 00:00:00-06', '2025-12-31 00:00:00-06', '38', '38', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('8', '25', '17', '18', '1', '90', '1', '48', '1', '001', 'Seguimiento a las actividades para cumplimiento de la agenda oficial de trabajo.', '1', '1', '12', '2025-04-01 00:00:00-06', '2025-12-31 00:00:00-06', '38', '38', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('14', '25', '24', '18', '1', '90', '1', '157', '1', '001', 'Administración de recursos humanos, materiales y financieros.', '1', '1', '12', '2025-04-01 00:00:00-06', '2025-12-31 00:00:00-06', '177', '177', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('1', '26', '17', '18', '1', '90', '1', '48', '1', '001', 'Seguimiento a las actividades para cumplimiento de la agenda oficial de trabajo.', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '7', '7', '2', 'false');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('17', '26', '24', '1', '1', '90', '1', '157', '1', '001', 'Promover acciones que contribuyan a una igualdad entre hombres y mujeres en el organismo.', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '177', '177', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('18', '26', '24', '18', '1', '90', '1', '157', '1', '001', 'Administración de recursos humanos, materiales y financieros.', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '177', '177', '2', 'false');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('16', '25', '15', '20', '1', '78', '1', '45', '1', '001', 'Administración de recursos humanos, materiales y financieros.', '1', '1', '12', '2025-01-01 00:00:00-06', '2025-12-31 00:00:00-06', '324', '324', '2', 'true');`,
        `INSERT INTO public.proyectos_estrategicos (id_proyecto_estrategico, "id_año_del_gasto", id_estructura_administrativa, id_clasificacion_funcional, id_programa_sectorial, id_programa_presupuestario, id_origen_de_asignacion, id_actividad_institucional, id_asignacion_del_gasto, proyecto_estrategico, nombre_tecnico, id_tipo_de_proyecto, id_cobertura, id_tipo_de_accion, inicio, termino, id_lider_del_proyecto, id_jefe_del_lider, id_estatus_del_proyecto, esta_borrado) VALUES ('6', '26', '23', '18', '1', '90', '1', '45', '1', '001', 'Seguimiento de las acciones del Gobierno del Estado de Chiapas en la Ciudad de México.', '2', '1', '12', '2026-01-01 00:00:00-06', '2026-12-31 00:00:00-06', '324', '324', '2', 'false');`
    ];

    try {
        await pool.query('BEGIN');
        for (const query of queries) {
            await pool.query(query);
            console.log('Executed:', query.substring(0, 100) + '...');
        }
        await pool.query('COMMIT');
        console.log('All inserts completed successfully.');
    } catch (error) {
        await pool.query('ROLLBACK');
        console.error('Error during insertion, transaction rolled back:', error);
    } finally {
        pool.end();
    }
}

insertData();
